// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (id, name, description, session)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, session, created_at, updated_at
`

type CreateCourseParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Session     Session     `json:"session"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Session,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Session,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const getAllCourses = `-- name: GetAllCourses :many
SELECT id, name, description, session, created_at, updated_at FROM courses LIMIT $1 OFFSET $2
`

type GetAllCoursesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllCourses(ctx context.Context, arg GetAllCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, getAllCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Session,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT id, name, description, session, created_at, updated_at FROM courses WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Session,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET name = $2, description = $3, session = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, session, created_at, updated_at
`

type UpdateCourseParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Session     Session     `json:"session"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Session,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Session,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
