// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrence-types.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOccurrenceType = `-- name: CreateOccurrenceType :one
INSERT INTO occurrence_types (id, code, description, severity)
VALUES ($1, $2, $3, $4)
RETURNING id, code, description, severity, created_at, updated_at
`

type CreateOccurrenceTypeParams struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Description string      `json:"description"`
	Severity    int32       `json:"severity"`
}

func (q *Queries) CreateOccurrenceType(ctx context.Context, arg CreateOccurrenceTypeParams) (OccurrenceType, error) {
	row := q.db.QueryRow(ctx, createOccurrenceType,
		arg.ID,
		arg.Code,
		arg.Description,
		arg.Severity,
	)
	var i OccurrenceType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Severity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOccurrenceType = `-- name: DeleteOccurrenceType :exec
DELETE FROM occurrence_types WHERE id = $1
`

func (q *Queries) DeleteOccurrenceType(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOccurrenceType, id)
	return err
}

const getAllOccurrenceTypes = `-- name: GetAllOccurrenceTypes :many
SELECT id, code, description, severity, created_at, updated_at FROM occurrence_types LIMIT $1 OFFSET $2
`

type GetAllOccurrenceTypesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllOccurrenceTypes(ctx context.Context, arg GetAllOccurrenceTypesParams) ([]OccurrenceType, error) {
	rows, err := q.db.Query(ctx, getAllOccurrenceTypes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OccurrenceType
	for rows.Next() {
		var i OccurrenceType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.Severity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOccurrenceTypeByID = `-- name: GetOccurrenceTypeByID :one
SELECT id, code, description, severity, created_at, updated_at FROM occurrence_types WHERE id = $1
`

func (q *Queries) GetOccurrenceTypeByID(ctx context.Context, id pgtype.UUID) (OccurrenceType, error) {
	row := q.db.QueryRow(ctx, getOccurrenceTypeByID, id)
	var i OccurrenceType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Severity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOccurrenceType = `-- name: UpdateOccurrenceType :one
UPDATE occurrence_types
SET code = $2, description = $3, severity = $4, updated_at = now()
WHERE id = $1
RETURNING id, code, description, severity, created_at, updated_at
`

type UpdateOccurrenceTypeParams struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Description string      `json:"description"`
	Severity    int32       `json:"severity"`
}

func (q *Queries) UpdateOccurrenceType(ctx context.Context, arg UpdateOccurrenceTypeParams) (OccurrenceType, error) {
	row := q.db.QueryRow(ctx, updateOccurrenceType,
		arg.ID,
		arg.Code,
		arg.Description,
		arg.Severity,
	)
	var i OccurrenceType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.Severity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
