// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddStudentGuardian(ctx context.Context, arg AddStudentGuardianParams) error
	AddStudentSubject(ctx context.Context, arg AddStudentSubjectParams) error
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error)
	CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error)
	CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (Occurrence, error)
	CreateOccurrenceType(ctx context.Context, arg CreateOccurrenceTypeParams) (OccurrenceType, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWarning(ctx context.Context, arg CreateWarningParams) (Warning, error)
	DeleteCourse(ctx context.Context, id pgtype.UUID) error
	DeleteEnrollment(ctx context.Context, id pgtype.UUID) error
	DeleteGuardian(ctx context.Context, id pgtype.UUID) error
	DeleteOccurrence(ctx context.Context, id pgtype.UUID) error
	DeleteOccurrenceType(ctx context.Context, id pgtype.UUID) error
	DeletePermission(ctx context.Context, id pgtype.UUID) error
	DeleteRefreshTokenByUserId(ctx context.Context, userID pgtype.UUID) error
	DeleteSchedule(ctx context.Context, id pgtype.UUID) error
	DeleteStudent(ctx context.Context, id pgtype.UUID) error
	DeleteSubject(ctx context.Context, id pgtype.UUID) error
	DeleteWarning(ctx context.Context, id pgtype.UUID) error
	GetAllCourses(ctx context.Context, arg GetAllCoursesParams) ([]Course, error)
	GetAllEnrollments(ctx context.Context, arg GetAllEnrollmentsParams) ([]Enrollment, error)
	GetAllOccurrenceTypes(ctx context.Context, arg GetAllOccurrenceTypesParams) ([]OccurrenceType, error)
	GetAllOccurrences(ctx context.Context, arg GetAllOccurrencesParams) ([]Occurrence, error)
	GetAllPermissions(ctx context.Context, arg GetAllPermissionsParams) ([]Permission, error)
	GetAllSchedules(ctx context.Context, arg GetAllSchedulesParams) ([]Schedule, error)
	GetAllStudents(ctx context.Context, arg GetAllStudentsParams) ([]Student, error)
	GetAllSubjects(ctx context.Context, arg GetAllSubjectsParams) ([]Subject, error)
	GetAllWarnings(ctx context.Context, arg GetAllWarningsParams) ([]Warning, error)
	GetCourseByID(ctx context.Context, id pgtype.UUID) (Course, error)
	GetEnrollmentByID(ctx context.Context, id pgtype.UUID) (Enrollment, error)
	GetGuardianByID(ctx context.Context, id pgtype.UUID) (Guardian, error)
	GetGuardians(ctx context.Context, arg GetGuardiansParams) ([]Guardian, error)
	GetOccurrenceByID(ctx context.Context, id pgtype.UUID) (Occurrence, error)
	GetOccurrenceTypeByID(ctx context.Context, id pgtype.UUID) (OccurrenceType, error)
	GetPermissionByID(ctx context.Context, id pgtype.UUID) (Permission, error)
	GetRefreshTokenByToken(ctx context.Context, arg GetRefreshTokenByTokenParams) (RefreshToken, error)
	GetRefreshTokenByUserId(ctx context.Context, arg GetRefreshTokenByUserIdParams) (RefreshToken, error)
	GetScheduleByID(ctx context.Context, id pgtype.UUID) (Schedule, error)
	GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error)
	GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error)
	GetUserByCode(ctx context.Context, code string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetWarningByID(ctx context.Context, id pgtype.UUID) (Warning, error)
	RemoveStudentGuardian(ctx context.Context, arg RemoveStudentGuardianParams) error
	RemoveStudentSubject(ctx context.Context, arg RemoveStudentSubjectParams) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (Enrollment, error)
	UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error)
	UpdateOccurrence(ctx context.Context, arg UpdateOccurrenceParams) (Occurrence, error)
	UpdateOccurrenceType(ctx context.Context, arg UpdateOccurrenceTypeParams) (OccurrenceType, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateWarning(ctx context.Context, arg UpdateWarningParams) (Warning, error)
}

var _ Querier = (*Queries)(nil)
