// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (id, cpf, ra, photo_url, name, email) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, cpf, ra, photo_url, name, email, created_at, updated_at
`

type CreateStudentParams struct {
	ID       pgtype.UUID `json:"id"`
	Cpf      string      `json:"cpf"`
	Ra       string      `json:"ra"`
	PhotoUrl pgtype.Text `json:"photo_url"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.ID,
		arg.Cpf,
		arg.Ra,
		arg.PhotoUrl,
		arg.Name,
		arg.Email,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Cpf,
		&i.Ra,
		&i.PhotoUrl,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM students WHERE id = $1
`

func (q *Queries) DeleteStudent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudent, id)
	return err
}

const getAllStudents = `-- name: GetAllStudents :many
SELECT id, cpf, ra, photo_url, name, email, created_at, updated_at FROM students LIMIT $1 OFFSET $2
`

type GetAllStudentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllStudents(ctx context.Context, arg GetAllStudentsParams) ([]Student, error) {
	rows, err := q.db.Query(ctx, getAllStudents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Cpf,
			&i.Ra,
			&i.PhotoUrl,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, cpf, ra, photo_url, name, email, created_at, updated_at FROM students WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id pgtype.UUID) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Cpf,
		&i.Ra,
		&i.PhotoUrl,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students SET cpf = $2, ra = $3, photo_url = $4, name = $5, email = $6, updated_at = now() WHERE id = $1 RETURNING id, cpf, ra, photo_url, name, email, created_at, updated_at
`

type UpdateStudentParams struct {
	ID       pgtype.UUID `json:"id"`
	Cpf      string      `json:"cpf"`
	Ra       string      `json:"ra"`
	PhotoUrl pgtype.Text `json:"photo_url"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, updateStudent,
		arg.ID,
		arg.Cpf,
		arg.Ra,
		arg.PhotoUrl,
		arg.Name,
		arg.Email,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.Cpf,
		&i.Ra,
		&i.PhotoUrl,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
