// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student-guardians.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStudentGuardian = `-- name: AddStudentGuardian :exec
INSERT INTO students_guardians (student_id, guardian_id)
VALUES ($1, $2)
ON CONFLICT (student_id, guardian_id) DO NOTHING
`

type AddStudentGuardianParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	GuardianID pgtype.UUID `json:"guardian_id"`
}

func (q *Queries) AddStudentGuardian(ctx context.Context, arg AddStudentGuardianParams) error {
	_, err := q.db.Exec(ctx, addStudentGuardian, arg.StudentID, arg.GuardianID)
	return err
}

const removeStudentGuardian = `-- name: RemoveStudentGuardian :exec
DELETE FROM students_guardians
WHERE student_id = $1 AND guardian_id = $2
`

type RemoveStudentGuardianParams struct {
	StudentID  pgtype.UUID `json:"student_id"`
	GuardianID pgtype.UUID `json:"guardian_id"`
}

func (q *Queries) RemoveStudentGuardian(ctx context.Context, arg RemoveStudentGuardianParams) error {
	_, err := q.db.Exec(ctx, removeStudentGuardian, arg.StudentID, arg.GuardianID)
	return err
}
