// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (id, student_id, course_id, year) VALUES ($1, $2, $3, $4) RETURNING id, student_id, course_id, year, created_at, updated_at
`

type CreateEnrollmentParams struct {
	ID        pgtype.UUID `json:"id"`
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	Year      int32       `json:"year"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment,
		arg.ID,
		arg.StudentID,
		arg.CourseID,
		arg.Year,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :exec
DELETE FROM enrollments WHERE id = $1
`

func (q *Queries) DeleteEnrollment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnrollment, id)
	return err
}

const getAllEnrollments = `-- name: GetAllEnrollments :many
SELECT id, student_id, course_id, year, created_at, updated_at FROM enrollments LIMIT $1 OFFSET $2
`

type GetAllEnrollmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllEnrollments(ctx context.Context, arg GetAllEnrollmentsParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, getAllEnrollments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Enrollment
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.CourseID,
			&i.Year,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrollmentByID = `-- name: GetEnrollmentByID :one
SELECT id, student_id, course_id, year, created_at, updated_at FROM enrollments WHERE id = $1
`

func (q *Queries) GetEnrollmentByID(ctx context.Context, id pgtype.UUID) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByID, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnrollment = `-- name: UpdateEnrollment :one
UPDATE enrollments SET student_id = $2, course_id = $3, year = $4, updated_at = now() WHERE id = $1 RETURNING id, student_id, course_id, year, created_at, updated_at
`

type UpdateEnrollmentParams struct {
	ID        pgtype.UUID `json:"id"`
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	Year      int32       `json:"year"`
}

func (q *Queries) UpdateEnrollment(ctx context.Context, arg UpdateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollment,
		arg.ID,
		arg.StudentID,
		arg.CourseID,
		arg.Year,
	)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.CourseID,
		&i.Year,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
