// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardians.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuardian = `-- name: CreateGuardian :one
INSERT INTO guardians (id, phone, email, name) VALUES ($1, $2, $3, $4) RETURNING id, phone, email, name, created_at, updated_at
`

type CreateGuardianParams struct {
	ID    pgtype.UUID `json:"id"`
	Phone string      `json:"phone"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) CreateGuardian(ctx context.Context, arg CreateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, createGuardian,
		arg.ID,
		arg.Phone,
		arg.Email,
		arg.Name,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGuardian = `-- name: DeleteGuardian :exec
DELETE FROM guardians WHERE id = $1
`

func (q *Queries) DeleteGuardian(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuardian, id)
	return err
}

const getGuardianByID = `-- name: GetGuardianByID :one
SELECT id, phone, email, name, created_at, updated_at FROM guardians WHERE id = $1
`

func (q *Queries) GetGuardianByID(ctx context.Context, id pgtype.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByID, id)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGuardians = `-- name: GetGuardians :many
SELECT id, phone, email, name, created_at, updated_at FROM guardians LIMIT $1 OFFSET $2
`

type GetGuardiansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetGuardians(ctx context.Context, arg GetGuardiansParams) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, getGuardians, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guardian
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuardian = `-- name: UpdateGuardian :one
UPDATE guardians SET phone = $2, email = $3, name = $4, updated_at = now() WHERE id = $1 RETURNING id, phone, email, name, created_at, updated_at
`

type UpdateGuardianParams struct {
	ID    pgtype.UUID `json:"id"`
	Phone string      `json:"phone"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) (Guardian, error) {
	row := q.db.QueryRow(ctx, updateGuardian,
		arg.ID,
		arg.Phone,
		arg.Email,
		arg.Name,
	)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
