// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type OccurrenceStatus string

const (
	OccurrenceStatusPENDING  OccurrenceStatus = "PENDING"
	OccurrenceStatusAPPROVED OccurrenceStatus = "APPROVED"
	OccurrenceStatusREPROVED OccurrenceStatus = "REPROVED"
)

func (e *OccurrenceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OccurrenceStatus(s)
	case string:
		*e = OccurrenceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OccurrenceStatus: %T", src)
	}
	return nil
}

type NullOccurrenceStatus struct {
	OccurrenceStatus OccurrenceStatus `json:"occurrence_status"`
	Valid            bool             `json:"valid"` // Valid is true if OccurrenceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOccurrenceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OccurrenceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OccurrenceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOccurrenceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OccurrenceStatus), nil
}

type PermissionType string

const (
	PermissionTypeLEAVE PermissionType = "LEAVE"
	PermissionTypeSTAY  PermissionType = "STAY"
)

func (e *PermissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionType(s)
	case string:
		*e = PermissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionType: %T", src)
	}
	return nil
}

type NullPermissionType struct {
	PermissionType PermissionType `json:"permission_type"`
	Valid          bool           `json:"valid"` // Valid is true if PermissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionType) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionType), nil
}

type Role string

const (
	RoleADMIN     Role = "ADMIN"
	RoleSUPPORT   Role = "SUPPORT"
	RoleRECEPTION Role = "RECEPTION"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Session string

const (
	SessionMORNING   Session = "MORNING"
	SessionAFTERNOON Session = "AFTERNOON"
	SessionEVENING   Session = "EVENING"
)

func (e *Session) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Session(s)
	case string:
		*e = Session(s)
	default:
		return fmt.Errorf("unsupported scan type for Session: %T", src)
	}
	return nil
}

type NullSession struct {
	Session Session `json:"session"`
	Valid   bool    `json:"valid"` // Valid is true if Session is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSession) Scan(value interface{}) error {
	if value == nil {
		ns.Session, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Session.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSession) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Session), nil
}

type Course struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Session     Session            `json:"session"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Enrollment struct {
	ID        pgtype.UUID        `json:"id"`
	StudentID pgtype.UUID        `json:"student_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	Year      int32              `json:"year"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Guardian struct {
	ID        pgtype.UUID        `json:"id"`
	Phone     string             `json:"phone"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Occurrence struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OccurrenceTypeID pgtype.UUID        `json:"occurrence_type_id"`
	StudentID        pgtype.UUID        `json:"student_id"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	UserRelatedID    pgtype.UUID        `json:"user_related_id"`
	Status           OccurrenceStatus   `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OccurrenceType struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Description string             `json:"description"`
	Severity    int32              `json:"severity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID           pgtype.UUID        `json:"id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	Type         PermissionType     `json:"type"`
	Description  string             `json:"description"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	Token     pgtype.UUID        `json:"token"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Schedule struct {
	ID        pgtype.UUID        `json:"id"`
	SubjectID pgtype.UUID        `json:"subject_id"`
	Session   Session            `json:"session"`
	DayOfWeek string             `json:"day_of_week"`
	StartTime pgtype.Time        `json:"start_time"`
	EndTime   pgtype.Time        `json:"end_time"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID        pgtype.UUID        `json:"id"`
	Cpf       string             `json:"cpf"`
	Ra        string             `json:"ra"`
	PhotoUrl  pgtype.Text        `json:"photo_url"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type StudentsGuardian struct {
	StudentID  pgtype.UUID        `json:"student_id"`
	GuardianID pgtype.UUID        `json:"guardian_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type StudentsSubject struct {
	SubjectID pgtype.UUID        `json:"subject_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Subject struct {
	ID        pgtype.UUID        `json:"id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	Name      string             `json:"name"`
	Semester  int32              `json:"semester"`
	Section   string             `json:"section"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Code           string             `json:"code"`
	HashedPassword string             `json:"hashed_password"`
	Role           Role               `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Warning struct {
	ID           pgtype.UUID        `json:"id"`
	OccurrenceID pgtype.UUID        `json:"occurrence_id"`
	Report       string             `json:"report"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
