// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: occurrences.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO occurrences (id, user_id, occurrence_type_id, student_id, occurred_at, user_related_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, occurrence_type_id, student_id, occurred_at, user_related_id, status, created_at, updated_at
`

type CreateOccurrenceParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OccurrenceTypeID pgtype.UUID        `json:"occurrence_type_id"`
	StudentID        pgtype.UUID        `json:"student_id"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	UserRelatedID    pgtype.UUID        `json:"user_related_id"`
	Status           OccurrenceStatus   `json:"status"`
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (Occurrence, error) {
	row := q.db.QueryRow(ctx, createOccurrence,
		arg.ID,
		arg.UserID,
		arg.OccurrenceTypeID,
		arg.StudentID,
		arg.OccurredAt,
		arg.UserRelatedID,
		arg.Status,
	)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurrenceTypeID,
		&i.StudentID,
		&i.OccurredAt,
		&i.UserRelatedID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOccurrence = `-- name: DeleteOccurrence :exec
DELETE FROM occurrences WHERE id = $1
`

func (q *Queries) DeleteOccurrence(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOccurrence, id)
	return err
}

const getAllOccurrences = `-- name: GetAllOccurrences :many
SELECT id, user_id, occurrence_type_id, student_id, occurred_at, user_related_id, status, created_at, updated_at FROM occurrences LIMIT $1 OFFSET $2
`

type GetAllOccurrencesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllOccurrences(ctx context.Context, arg GetAllOccurrencesParams) ([]Occurrence, error) {
	rows, err := q.db.Query(ctx, getAllOccurrences, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Occurrence
	for rows.Next() {
		var i Occurrence
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OccurrenceTypeID,
			&i.StudentID,
			&i.OccurredAt,
			&i.UserRelatedID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOccurrenceByID = `-- name: GetOccurrenceByID :one
SELECT id, user_id, occurrence_type_id, student_id, occurred_at, user_related_id, status, created_at, updated_at FROM occurrences WHERE id = $1
`

func (q *Queries) GetOccurrenceByID(ctx context.Context, id pgtype.UUID) (Occurrence, error) {
	row := q.db.QueryRow(ctx, getOccurrenceByID, id)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurrenceTypeID,
		&i.StudentID,
		&i.OccurredAt,
		&i.UserRelatedID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOccurrence = `-- name: UpdateOccurrence :one
UPDATE occurrences
SET user_id = $2, occurrence_type_id = $3, student_id = $4, occurred_at = $5, user_related_id = $6, status = $7
WHERE id = $1
RETURNING id, user_id, occurrence_type_id, student_id, occurred_at, user_related_id, status, created_at, updated_at
`

type UpdateOccurrenceParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OccurrenceTypeID pgtype.UUID        `json:"occurrence_type_id"`
	StudentID        pgtype.UUID        `json:"student_id"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	UserRelatedID    pgtype.UUID        `json:"user_related_id"`
	Status           OccurrenceStatus   `json:"status"`
}

func (q *Queries) UpdateOccurrence(ctx context.Context, arg UpdateOccurrenceParams) (Occurrence, error) {
	row := q.db.QueryRow(ctx, updateOccurrence,
		arg.ID,
		arg.UserID,
		arg.OccurrenceTypeID,
		arg.StudentID,
		arg.OccurredAt,
		arg.UserRelatedID,
		arg.Status,
	)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OccurrenceTypeID,
		&i.StudentID,
		&i.OccurredAt,
		&i.UserRelatedID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
