// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (id, student_id, type, description, requested_at, scheduled_for)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, student_id, type, description, requested_at, scheduled_for, created_at, updated_at
`

type CreatePermissionParams struct {
	ID           pgtype.UUID        `json:"id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	Type         PermissionType     `json:"type"`
	Description  string             `json:"description"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.ID,
		arg.StudentID,
		arg.Type,
		arg.Description,
		arg.RequestedAt,
		arg.ScheduledFor,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Type,
		&i.Description,
		&i.RequestedAt,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, student_id, type, description, requested_at, scheduled_for, created_at, updated_at FROM permissions LIMIT $1 OFFSET $2
`

type GetAllPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllPermissions(ctx context.Context, arg GetAllPermissionsParams) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.Type,
			&i.Description,
			&i.RequestedAt,
			&i.ScheduledFor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, student_id, type, description, requested_at, scheduled_for, created_at, updated_at FROM permissions WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id pgtype.UUID) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Type,
		&i.Description,
		&i.RequestedAt,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET student_id = $2, type = $3, description = $4, requested_at = $5, scheduled_for = $6, updated_at = now()
WHERE id = $1
RETURNING id, student_id, type, description, requested_at, scheduled_for, created_at, updated_at
`

type UpdatePermissionParams struct {
	ID           pgtype.UUID        `json:"id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	Type         PermissionType     `json:"type"`
	Description  string             `json:"description"`
	RequestedAt  pgtype.Timestamptz `json:"requested_at"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.ID,
		arg.StudentID,
		arg.Type,
		arg.Description,
		arg.RequestedAt,
		arg.ScheduledFor,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.Type,
		&i.Description,
		&i.RequestedAt,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
