// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (id, subject_id, session, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, subject_id, session, day_of_week, start_time, end_time, created_at, updated_at
`

type CreateScheduleParams struct {
	ID        pgtype.UUID `json:"id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	Session   Session     `json:"session"`
	DayOfWeek string      `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.ID,
		arg.SubjectID,
		arg.Session,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Session,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const getAllSchedules = `-- name: GetAllSchedules :many
SELECT id, subject_id, session, day_of_week, start_time, end_time, created_at, updated_at FROM schedules LIMIT $1 OFFSET $2
`

type GetAllSchedulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllSchedules(ctx context.Context, arg GetAllSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, getAllSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Session,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, subject_id, session, day_of_week, start_time, end_time, created_at, updated_at FROM schedules WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Session,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET subject_id = $2, session = $3, day_of_week = $4, start_time = $5, end_time = $6, updated_at = now()
WHERE id = $1
RETURNING id, subject_id, session, day_of_week, start_time, end_time, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID        pgtype.UUID `json:"id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	Session   Session     `json:"session"`
	DayOfWeek string      `json:"day_of_week"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.SubjectID,
		arg.Session,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Session,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
