// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student-subjects.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addStudentSubject = `-- name: AddStudentSubject :exec
INSERT INTO students_subjects (student_id, subject_id)
VALUES ($1, $2)
ON CONFLICT (student_id, subject_id) DO NOTHING
`

type AddStudentSubjectParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

func (q *Queries) AddStudentSubject(ctx context.Context, arg AddStudentSubjectParams) error {
	_, err := q.db.Exec(ctx, addStudentSubject, arg.StudentID, arg.SubjectID)
	return err
}

const removeStudentSubject = `-- name: RemoveStudentSubject :exec
DELETE FROM students_subjects
WHERE student_id = $1 AND subject_id = $2
`

type RemoveStudentSubjectParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
}

func (q *Queries) RemoveStudentSubject(ctx context.Context, arg RemoveStudentSubjectParams) error {
	_, err := q.db.Exec(ctx, removeStudentSubject, arg.StudentID, arg.SubjectID)
	return err
}
