// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (id, course_id, name, semester, section)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, name, semester, section, created_at, updated_at
`

type CreateSubjectParams struct {
	ID       pgtype.UUID `json:"id"`
	CourseID pgtype.UUID `json:"course_id"`
	Name     string      `json:"name"`
	Semester int32       `json:"semester"`
	Section  string      `json:"section"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject,
		arg.ID,
		arg.CourseID,
		arg.Name,
		arg.Semester,
		arg.Section,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Semester,
		&i.Section,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects WHERE id = $1
`

func (q *Queries) DeleteSubject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubject, id)
	return err
}

const getAllSubjects = `-- name: GetAllSubjects :many
SELECT id, course_id, name, semester, section, created_at, updated_at FROM subjects LIMIT $1 OFFSET $2
`

type GetAllSubjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllSubjects(ctx context.Context, arg GetAllSubjectsParams) ([]Subject, error) {
	rows, err := q.db.Query(ctx, getAllSubjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Name,
			&i.Semester,
			&i.Section,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectByID = `-- name: GetSubjectByID :one
SELECT id, course_id, name, semester, section, created_at, updated_at FROM subjects WHERE id = $1
`

func (q *Queries) GetSubjectByID(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Semester,
		&i.Section,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET name = $2,
    semester = $3,
    section = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, course_id, name, semester, section, created_at, updated_at
`

type UpdateSubjectParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Semester int32       `json:"semester"`
	Section  string      `json:"section"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.ID,
		arg.Name,
		arg.Semester,
		arg.Section,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Name,
		&i.Semester,
		&i.Section,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
