// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, code, hashed_password, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, code, hashed_password, role, created_at, updated_at
`

type CreateUserParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Code           string      `json:"code"`
	HashedPassword string      `json:"hashed_password"`
	Role           Role        `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByCode = `-- name: GetUserByCode :one
SELECT id, name, code, hashed_password, role, created_at, updated_at FROM users WHERE code = $1
`

func (q *Queries) GetUserByCode(ctx context.Context, code string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCode, code)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, code, hashed_password, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.HashedPassword,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
