// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: warnings.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWarning = `-- name: CreateWarning :one
INSERT INTO warnings (id, occurrence_id, report) VALUES ($1, $2, $3) RETURNING id, occurrence_id, report, created_at, updated_at
`

type CreateWarningParams struct {
	ID           pgtype.UUID `json:"id"`
	OccurrenceID pgtype.UUID `json:"occurrence_id"`
	Report       string      `json:"report"`
}

func (q *Queries) CreateWarning(ctx context.Context, arg CreateWarningParams) (Warning, error) {
	row := q.db.QueryRow(ctx, createWarning, arg.ID, arg.OccurrenceID, arg.Report)
	var i Warning
	err := row.Scan(
		&i.ID,
		&i.OccurrenceID,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWarning = `-- name: DeleteWarning :exec
DELETE FROM warnings WHERE id = $1
`

func (q *Queries) DeleteWarning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWarning, id)
	return err
}

const getAllWarnings = `-- name: GetAllWarnings :many
SELECT id, occurrence_id, report, created_at, updated_at FROM warnings LIMIT $1 OFFSET $2
`

type GetAllWarningsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllWarnings(ctx context.Context, arg GetAllWarningsParams) ([]Warning, error) {
	rows, err := q.db.Query(ctx, getAllWarnings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Warning
	for rows.Next() {
		var i Warning
		if err := rows.Scan(
			&i.ID,
			&i.OccurrenceID,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarningByID = `-- name: GetWarningByID :one
SELECT id, occurrence_id, report, created_at, updated_at FROM warnings WHERE id = $1
`

func (q *Queries) GetWarningByID(ctx context.Context, id pgtype.UUID) (Warning, error) {
	row := q.db.QueryRow(ctx, getWarningByID, id)
	var i Warning
	err := row.Scan(
		&i.ID,
		&i.OccurrenceID,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWarning = `-- name: UpdateWarning :one
UPDATE warnings SET occurrence_id = $2, report = $3, updated_at = now() WHERE id = $1 RETURNING id, occurrence_id, report, created_at, updated_at
`

type UpdateWarningParams struct {
	ID           pgtype.UUID `json:"id"`
	OccurrenceID pgtype.UUID `json:"occurrence_id"`
	Report       string      `json:"report"`
}

func (q *Queries) UpdateWarning(ctx context.Context, arg UpdateWarningParams) (Warning, error) {
	row := q.db.QueryRow(ctx, updateWarning, arg.ID, arg.OccurrenceID, arg.Report)
	var i Warning
	err := row.Scan(
		&i.ID,
		&i.OccurrenceID,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
